import { createFileRoute } from '@tanstack/react-router';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Activity, Plus, Target } from 'lucide-react';
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card';
import { Button } from '~/components/ui/button';
import { Input } from '~/components/ui/input';
import { Badge } from '~/components/ui/badge';
import { api } from '~/lib/api';
import { useProject } from '~/lib/project-context';
import { QueryErrorState } from '~/components/query-error-state';

export const Route = createFileRoute('/$organizationSlug/operations')({ component: Operations });

interface Service{id:string;name:string;}
interface Environment{id:string;name:string;kind:string;}
interface Operation{id:string;name:string;slug:string;serviceId:string;environmentId:string|null;description:string|null;method:string|null;routePattern:string|null;criticality:string;sloMetric:string|null;sloTarget:number|null;sloUnit:string|null;}

function Operations(){
 const {projectId}=useProject(); const [name,setName]=useState('');const [slug,setSlug]=useState('');const [serviceId,setServiceId]=useState('');const [environmentId,setEnvironmentId]=useState('');const [method,setMethod]=useState('GET');const [routePattern,setRoutePattern]=useState('');const [criticality,setCriticality]=useState('medium');const [sloMetric,setSloMetric]=useState('');const [sloTarget,setSloTarget]=useState('');
 const services=useQuery({queryKey:['services',projectId],queryFn:()=>api.get<Service[]>(`/services?projectId=${projectId}`),enabled:!!projectId});const envs=useQuery({queryKey:['environments',projectId],queryFn:()=>api.get<Environment[]>(`/environments?projectId=${projectId}`),enabled:!!projectId});const ops=useQuery({queryKey:['operations',projectId],queryFn:()=>api.get<Operation[]>(`/business-operations?projectId=${projectId}`),enabled:!!projectId});
 const create=useMutation({mutationFn:()=>api.post<Operation>(`/business-operations?projectId=${projectId}`,{name,slug,serviceId,environmentId:environmentId||undefined,method,routePattern:routePattern||undefined,criticality,sloMetric:sloMetric||undefined,sloTarget:sloTarget?Number(sloTarget):undefined,sloUnit:sloMetric?'%':undefined}),onSuccess:()=>{setName('');setSlug('');setRoutePattern('');setSloTarget('');void ops.refetch();}});
 if(!projectId)return <Card><CardContent className="p-10 text-center">Choose a project</CardContent></Card>;if(services.isError||envs.isError)return <QueryErrorState onRetry={()=>{void services.refetch();void envs.refetch();}} />;
 return <div className="mx-auto w-full space-y-6 pb-10"><h1 className="sr-only">Operations</h1>
 <Card className="border-[#242426] bg-[#0B0B0C] shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Plus className="h-4 w-4 text-[#ACFC15]"/>Define operation</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 lg:grid-cols-4"><Input placeholder="Checkout" value={name} onChange={e=>setName(e.target.value)}/><Input placeholder="checkout" value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))}/><select value={serviceId} onChange={e=>setServiceId(e.target.value)} className="h-10 rounded-md border border-[#242426] bg-[#151517] px-3 text-sm"><option value="">Service</option>{services.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={environmentId} onChange={e=>setEnvironmentId(e.target.value)} className="h-10 rounded-md border border-[#242426] bg-[#151517] px-3 text-sm"><option value="">Environment</option>{envs.data?.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><Input placeholder="Route pattern" value={routePattern} onChange={e=>setRoutePattern(e.target.value)}/><Input placeholder="HTTP method" value={method} onChange={e=>setMethod(e.target.value.toUpperCase())}/><select value={criticality} onChange={e=>setCriticality(e.target.value)} className="h-10 rounded-md border border-[#242426] bg-[#151517] px-3 text-sm"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select><div className="flex gap-2"><select value={sloMetric} onChange={e=>setSloMetric(e.target.value)} className="h-10 flex-1 rounded-md border border-[#242426] bg-[#151517] px-3 text-sm"><option value="">No SLO</option><option value="availability">Availability</option><option value="latency">Latency</option><option value="error_rate">Error rate</option></select><Input className="w-28" placeholder="Target" value={sloTarget} onChange={e=>setSloTarget(e.target.value)}/></div><Button className="lg:col-span-4" onClick={()=>create.mutate()} disabled={!name||!slug||!serviceId||create.isPending}><Plus className="mr-2 h-4 w-4"/>Create operation</Button></CardContent></Card>
 <Card className="overflow-hidden border-[#242426] bg-[#0B0B0C] shadow-none"><CardHeader className="border-b bg-[#151517]"><CardTitle className="text-base">Critical flows</CardTitle></CardHeader><CardContent className="p-0">{!ops.data?.length?<div className="p-10 text-center text-sm text-[#989898]">No business operations defined yet.</div>:<div className="divide-y divide-[#242426]">{ops.data.map(op=><div key={op.id} className="flex flex-wrap items-center gap-4 p-4"><div className="grid h-9 w-9 place-items-center rounded-lg bg-secondary"><Target className="h-4 w-4"/></div><div className="min-w-0 flex-1"><p className="text-sm font-medium">{op.name}</p><p className="mt-1 font-mono text-xs text-[#989898]">{op.method??'—'} {op.routePattern??op.slug}</p></div><Badge variant="outline">{op.criticality}</Badge>{op.sloMetric&&<span className="text-xs text-[#989898]">SLO {op.sloTarget??'—'} {op.sloUnit??''} {op.sloMetric}</span>}<Activity className="h-4 w-4 text-[#16931F]"/></div>)}</div>}</CardContent></Card>
 </div>;
}