import { createFileRoute, Link } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, GitBranch, Clock3, FileText } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card';
import { Skeleton } from '~/components/ui/skeleton';
import { Badge } from '~/components/ui/badge';
import { api } from '~/lib/api';
import { QueryErrorState } from '~/components/query-error-state';
import { useProject } from '~/lib/project-context';
export const Route=createFileRoute('/$organizationSlug/trace/$traceId')({component:TraceDetail});
interface Span{id:string;traceId:string;parentSpanId:string|null;service:string;operation:string;durationMs:number;startTime:string;status:string;attributes:Record<string,unknown>|null;events:Array<{name:string;timestamp:string}>;}
function TraceDetail(){const {projectId,orgSlug}=useProject();const {traceId}=Route.useParams();const {data,isLoading,isError,refetch}=useQuery({queryKey:['trace',projectId,traceId],queryFn:()=>api.get<Span[]>(`/traces/${traceId}?projectId=${projectId}`),enabled:!!projectId&&!!traceId});if(!projectId)return <Card><CardContent className="p-10 text-center">Choose a project</CardContent></Card>;if(isError)return <QueryErrorState onRetry={() => void refetch()} />;return <div className="mx-auto max-w-[1400px] space-y-6 pb-10"><Link to="/$organizationSlug/traces" params={{organizationSlug:orgSlug!}} className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Traces</Link><header><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#16931F]">Trace detail</p><h1 className="mt-1 font-mono text-xl font-semibold break-all">{traceId}</h1></header>{isLoading?<Skeleton className="h-[500px]"/>:!data?.length?<Card><CardContent className="p-12 text-center"><p className="font-medium">Trace not found</p></CardContent></Card>:<Card className="overflow-hidden border-border shadow-none"><CardHeader className="border-b bg-muted"><CardTitle className="text-base">Span waterfall</CardTitle></CardHeader><CardContent className="p-0">{data.map((span,index)=><div key={span.id} className="grid grid-cols-1 gap-3 border-b sm:grid-cols-[minmax(180px,1fr)_120px_90px] sm:items-center sm:gap-4 border-border p-4 last:border-0"><div className="flex items-center gap-3" style={{paddingLeft:`${Math.min(index*16,96)}px`}}><GitBranch className="h-3.5 w-3.5 text-[#16931F]"/><div><p className="text-sm font-medium">{span.operation}</p><p className="text-xs text-muted-foreground">{span.service}</p></div></div><div className="flex items-center gap-2"><Clock3 className="h-3.5 w-3.5 text-muted-foreground"/><span className="font-mono text-xs">{span.durationMs}ms</span></div><Badge variant="outline">{span.status}</Badge><div className="col-span-full ml-8 flex flex-wrap gap-3 text-xs text-muted-foreground">{span.events?.length>0&&<span className="inline-flex items-center gap-1"><FileText className="h-3 w-3"/>{span.events.length} events</span>}{span.attributes&&Object.keys(span.attributes).slice(0,4).map(k=><span key={k} className="font-mono">{k}={String(span.attributes?.[k])}</span>)}</div></div>)}</CardContent></Card>}</div>}
