import { createFileRoute, Link } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { Search, GitBranch, Clock3, ChevronRight } from 'lucide-react';
import { useState } from 'react';
import { Card, CardContent } from '~/components/ui/card';
import { Input } from '~/components/ui/input';
import { Skeleton } from '~/components/ui/skeleton';
import { Badge } from '~/components/ui/badge';
import { api } from '~/lib/api';
import { QueryErrorState } from '~/components/query-error-state';
import { useProject } from '~/lib/project-context';

export const Route = createFileRoute('/$organizationSlug/traces')({ component: TraceExplorer });
interface Trace { traceId:string; name:string; start:string; end:string; spanCount:number; }
function TraceExplorer(){const {projectId,orgSlug}=useProject();const [q,setQ]=useState('');const {data,isLoading,isError,refetch}=useQuery({queryKey:['traces',projectId,q],queryFn:()=>api.get<{data:Trace[];nextCursor?:string}>(`/traces?projectId=${projectId}${q?`&q=${encodeURIComponent(q)}`:''}`),enabled:!!projectId});if(!projectId)return <Empty/>;if(isError)return <QueryErrorState onRetry={() => void refetch()} />;return <div className="mx-auto w-full space-y-6 pb-10"><h1 className="sr-only">Traces</h1><Card className="border-[#242426] shadow-none"><CardContent className="p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#989898]"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search trace ID, service, or operation" className="bg-[#151517] pl-9" aria-label="Search traces"/></div></CardContent></Card><Card className="overflow-hidden border-[#242426] shadow-none"><CardContent className="p-0">{isLoading?<div className="space-y-2 p-4">{Array.from({length:7}).map((_,i)=><Skeleton key={i} className="h-14"/>)}</div>:!data?.data?.length?<div className="p-12 text-center"><GitBranch className="mx-auto h-8 w-8 text-[#16931F]"/><p className="mt-3 font-medium">{q ? 'No traces found' : 'Waiting for your first trace'}</p><p className="mt-1 text-sm text-[#989898]">{q ? 'Try a broader search or another trace ID, service, or operation.' : 'Send a real request through your project instrumentation to activate trace exploration.'}</p>{!q&&<Link to="/onboarding" className="mt-4 inline-flex text-sm font-medium text-[#16931F] hover:underline">Open setup flow</Link>}</div>:<div className="divide-y divide-[#DBE5D7]">{data.data.map(t=><Link key={t.traceId} to="/$organizationSlug/trace/$traceId" params={{organizationSlug: orgSlug!, traceId:t.traceId}} className="flex items-center gap-4 p-4 hover:bg-[#151517] focus-visible:bg-[#151517]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-secondary"><GitBranch className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{t.name || t.traceId}</p><p className="font-mono text-[11px] text-[#989898]">{t.traceId} · {'distributed trace'}</p></div><div className="hidden items-center gap-2 sm:flex"><Clock3 className="h-3.5 w-3.5 text-[#989898]"/><span className="font-mono text-xs">{Math.max(0, new Date(t.end).getTime() - new Date(t.start).getTime())}ms</span><Badge variant="outline">{t.spanCount} spans</Badge></div><ChevronRight className="h-4 w-4 text-[#989898]"/></Link>)}</div>}</CardContent></Card></div>}
function Empty(){return <Card><CardContent className="p-10 text-center"><p className="font-medium">Choose a project</p><p className="mt-1 text-sm text-[#989898]">Select a project to inspect traces.</p></CardContent></Card>}
