/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationSlugRouteImport } from './routes/$organizationSlug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardDetectionsRouteImport } from './routes/dashboard/detections'
import { Route as DashboardErrorsRouteImport } from './routes/dashboard/errors'
import { Route as DashboardInvestigationsRouteImport } from './routes/dashboard/investigations'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/layout'
import { Route as DashboardLogsRouteImport } from './routes/dashboard/logs'
import { Route as DashboardServicesRouteImport } from './routes/dashboard/services'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardTracesRouteImport } from './routes/dashboard/traces'
import { Route as DashboardInvestigationsInvestigationIdRouteImport } from './routes/dashboard/investigations.$investigationId'
import { Route as DashboardServiceServiceIdRouteImport } from './routes/dashboard/service.$serviceId'
import { Route as DashboardTraceTraceIdRouteImport } from './routes/dashboard/trace.$traceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugRoute = OrganizationSlugRouteImport.update({
  id: '/$organizationSlug',
  path: '/$organizationSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDetectionsRoute = DashboardDetectionsRouteImport.update({
  id: '/dashboard/detections',
  path: '/dashboard/detections',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardErrorsRoute = DashboardErrorsRouteImport.update({
  id: '/dashboard/errors',
  path: '/dashboard/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvestigationsRoute = DashboardInvestigationsRouteImport.update({
  id: '/dashboard/investigations',
  path: '/dashboard/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/layout',
  path: '/dashboard/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/dashboard/logs',
  path: '/dashboard/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/dashboard/services',
  path: '/dashboard/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTracesRoute = DashboardTracesRouteImport.update({
  id: '/dashboard/traces',
  path: '/dashboard/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvestigationsInvestigationIdRoute =
  DashboardInvestigationsInvestigationIdRouteImport.update({
    id: '/$investigationId',
    path: '/$investigationId',
    getParentRoute: () => DashboardInvestigationsRoute,
  } as any)
const DashboardServiceServiceIdRoute =
  DashboardServiceServiceIdRouteImport.update({
    id: '/dashboard/service/$serviceId',
    path: '/dashboard/service/$serviceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTraceTraceIdRoute = DashboardTraceTraceIdRouteImport.update({
  id: '/dashboard/trace/$traceId',
  path: '/dashboard/trace/$traceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$organizationSlug': typeof OrganizationSlugRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/detections': typeof DashboardDetectionsRoute
  '/dashboard/errors': typeof DashboardErrorsRoute
  '/dashboard/investigations': typeof DashboardInvestigationsRouteWithChildren
  '/dashboard/layout': typeof DashboardLayoutRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/traces': typeof DashboardTracesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/investigations/$investigationId': typeof DashboardInvestigationsInvestigationIdRoute
  '/dashboard/service/$serviceId': typeof DashboardServiceServiceIdRoute
  '/dashboard/trace/$traceId': typeof DashboardTraceTraceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$organizationSlug': typeof OrganizationSlugRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/detections': typeof DashboardDetectionsRoute
  '/dashboard/errors': typeof DashboardErrorsRoute
  '/dashboard/investigations': typeof DashboardInvestigationsRouteWithChildren
  '/dashboard/layout': typeof DashboardLayoutRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/traces': typeof DashboardTracesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/investigations/$investigationId': typeof DashboardInvestigationsInvestigationIdRoute
  '/dashboard/service/$serviceId': typeof DashboardServiceServiceIdRoute
  '/dashboard/trace/$traceId': typeof DashboardTraceTraceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$organizationSlug': typeof OrganizationSlugRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/detections': typeof DashboardDetectionsRoute
  '/dashboard/errors': typeof DashboardErrorsRoute
  '/dashboard/investigations': typeof DashboardInvestigationsRouteWithChildren
  '/dashboard/layout': typeof DashboardLayoutRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/traces': typeof DashboardTracesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/investigations/$investigationId': typeof DashboardInvestigationsInvestigationIdRoute
  '/dashboard/service/$serviceId': typeof DashboardServiceServiceIdRoute
  '/dashboard/trace/$traceId': typeof DashboardTraceTraceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/register'
    | '/auth/callback'
    | '/dashboard/detections'
    | '/dashboard/errors'
    | '/dashboard/investigations'
    | '/dashboard/layout'
    | '/dashboard/logs'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/traces'
    | '/dashboard/'
    | '/dashboard/investigations/$investigationId'
    | '/dashboard/service/$serviceId'
    | '/dashboard/trace/$traceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/register'
    | '/auth/callback'
    | '/dashboard/detections'
    | '/dashboard/errors'
    | '/dashboard/investigations'
    | '/dashboard/layout'
    | '/dashboard/logs'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/traces'
    | '/dashboard'
    | '/dashboard/investigations/$investigationId'
    | '/dashboard/service/$serviceId'
    | '/dashboard/trace/$traceId'
  id:
    | '__root__'
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/register'
    | '/auth/callback'
    | '/dashboard/detections'
    | '/dashboard/errors'
    | '/dashboard/investigations'
    | '/dashboard/layout'
    | '/dashboard/logs'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/dashboard/traces'
    | '/dashboard/'
    | '/dashboard/investigations/$investigationId'
    | '/dashboard/service/$serviceId'
    | '/dashboard/trace/$traceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationSlugRoute: typeof OrganizationSlugRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizationsRoute: typeof OrganizationsRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DashboardDetectionsRoute: typeof DashboardDetectionsRoute
  DashboardErrorsRoute: typeof DashboardErrorsRoute
  DashboardInvestigationsRoute: typeof DashboardInvestigationsRouteWithChildren
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTracesRoute: typeof DashboardTracesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardServiceServiceIdRoute: typeof DashboardServiceServiceIdRoute
  DashboardTraceTraceIdRoute: typeof DashboardTraceTraceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug': {
      id: '/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof OrganizationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/detections': {
      id: '/dashboard/detections'
      path: '/dashboard/detections'
      fullPath: '/dashboard/detections'
      preLoaderRoute: typeof DashboardDetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/errors': {
      id: '/dashboard/errors'
      path: '/dashboard/errors'
      fullPath: '/dashboard/errors'
      preLoaderRoute: typeof DashboardErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/investigations': {
      id: '/dashboard/investigations'
      path: '/dashboard/investigations'
      fullPath: '/dashboard/investigations'
      preLoaderRoute: typeof DashboardInvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/layout': {
      id: '/dashboard/layout'
      path: '/dashboard/layout'
      fullPath: '/dashboard/layout'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/dashboard/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/dashboard/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/traces': {
      id: '/dashboard/traces'
      path: '/dashboard/traces'
      fullPath: '/dashboard/traces'
      preLoaderRoute: typeof DashboardTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/investigations/$investigationId': {
      id: '/dashboard/investigations/$investigationId'
      path: '/$investigationId'
      fullPath: '/dashboard/investigations/$investigationId'
      preLoaderRoute: typeof DashboardInvestigationsInvestigationIdRouteImport
      parentRoute: typeof DashboardInvestigationsRoute
    }
    '/dashboard/service/$serviceId': {
      id: '/dashboard/service/$serviceId'
      path: '/dashboard/service/$serviceId'
      fullPath: '/dashboard/service/$serviceId'
      preLoaderRoute: typeof DashboardServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trace/$traceId': {
      id: '/dashboard/trace/$traceId'
      path: '/dashboard/trace/$traceId'
      fullPath: '/dashboard/trace/$traceId'
      preLoaderRoute: typeof DashboardTraceTraceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardInvestigationsRouteChildren {
  DashboardInvestigationsInvestigationIdRoute: typeof DashboardInvestigationsInvestigationIdRoute
}

const DashboardInvestigationsRouteChildren: DashboardInvestigationsRouteChildren =
  {
    DashboardInvestigationsInvestigationIdRoute:
      DashboardInvestigationsInvestigationIdRoute,
  }

const DashboardInvestigationsRouteWithChildren =
  DashboardInvestigationsRoute._addFileChildren(
    DashboardInvestigationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationSlugRoute: OrganizationSlugRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrganizationsRoute: OrganizationsRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DashboardDetectionsRoute: DashboardDetectionsRoute,
  DashboardErrorsRoute: DashboardErrorsRoute,
  DashboardInvestigationsRoute: DashboardInvestigationsRouteWithChildren,
  DashboardLayoutRoute: DashboardLayoutRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTracesRoute: DashboardTracesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardServiceServiceIdRoute: DashboardServiceServiceIdRoute,
  DashboardTraceTraceIdRoute: DashboardTraceTraceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
