/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// Regenerated for the organization-scoped dashboard routes.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationSlugRouteImport } from './routes/$organizationSlug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardRouteImport } from './routes/$organizationSlug/dashboard'
import { Route as OrganizationIndexRouteImport } from './routes/$organizationSlug/index'
import { Route as DetectionsRouteImport } from './routes/$organizationSlug/detections'
import { Route as ErrorsRouteImport } from './routes/$organizationSlug/errors'
import { Route as InvestigationsRouteImport } from './routes/$organizationSlug/investigations'
import { Route as LogsRouteImport } from './routes/$organizationSlug/logs'
import { Route as ServicesRouteImport } from './routes/$organizationSlug/services'
import { Route as SettingsRouteImport } from './routes/$organizationSlug/settings'
import { Route as TracesRouteImport } from './routes/$organizationSlug/traces'
import { Route as InvestigationDetailRouteImport } from './routes/$organizationSlug/investigations.$investigationId'
import { Route as ServiceDetailRouteImport } from './routes/$organizationSlug/service.$serviceId'
import { Route as TraceDetailRouteImport } from './routes/$organizationSlug/trace.$traceId'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const OrganizationSlugRoute = OrganizationSlugRouteImport.update({ id: '/$organizationSlug', path: '/$organizationSlug', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const OnboardingRoute = OnboardingRouteImport.update({ id: '/onboarding', path: '/onboarding', getParentRoute: () => rootRouteImport } as any)
const OrganizationsRoute = OrganizationsRouteImport.update({ id: '/organizations', path: '/organizations', getParentRoute: () => rootRouteImport } as any)
const RegisterRoute = RegisterRouteImport.update({ id: '/register', path: '/register', getParentRoute: () => rootRouteImport } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({ id: '/auth/callback', path: '/auth/callback', getParentRoute: () => rootRouteImport } as any)

const DashboardRoute = DashboardRouteImport.update({
  id: '/$organizationSlug/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrganizationSlugRoute,
} as any)
const DashboardIndexRoute = OrganizationIndexRouteImport.update({
  id: '/$organizationSlug/dashboard/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDetectionsRoute = DetectionsRouteImport.update({
  id: '/$organizationSlug/dashboard/detections',
  path: '/detections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardErrorsRoute = ErrorsRouteImport.update({
  id: '/$organizationSlug/dashboard/errors',
  path: '/errors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvestigationsRoute = InvestigationsRouteImport.update({
  id: '/$organizationSlug/dashboard/investigations',
  path: '/investigations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = LogsRouteImport.update({
  id: '/$organizationSlug/dashboard/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = ServicesRouteImport.update({
  id: '/$organizationSlug/dashboard/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = SettingsRouteImport.update({
  id: '/$organizationSlug/dashboard/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTracesRoute = TracesRouteImport.update({
  id: '/$organizationSlug/dashboard/traces',
  path: '/traces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvestigationsInvestigationIdRoute = InvestigationDetailRouteImport.update({
  id: '/$organizationSlug/dashboard/investigations/$investigationId',
  path: '/$investigationId',
  getParentRoute: () => DashboardInvestigationsRoute,
} as any)
const DashboardServiceServiceIdRoute = ServiceDetailRouteImport.update({
  id: '/$organizationSlug/dashboard/service/$serviceId',
  path: '/service/$serviceId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTraceTraceIdRoute = TraceDetailRouteImport.update({
  id: '/$organizationSlug/dashboard/trace/$traceId',
  path: '/trace/$traceId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$organizationSlug': typeof OrganizationSlugRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$organizationSlug/dashboard': typeof DashboardRouteWithChildren
  '/$organizationSlug/dashboard/detections': typeof DashboardDetectionsRoute
  '/$organizationSlug/dashboard/errors': typeof DashboardErrorsRoute
  '/$organizationSlug/dashboard/investigations': typeof DashboardInvestigationsRouteWithChildren
  '/$organizationSlug/dashboard/logs': typeof DashboardLogsRoute
  '/$organizationSlug/dashboard/services': typeof DashboardServicesRoute
  '/$organizationSlug/dashboard/settings': typeof DashboardSettingsRoute
  '/$organizationSlug/dashboard/traces': typeof DashboardTracesRoute
  '/$organizationSlug/dashboard/': typeof DashboardIndexRoute
  '/$organizationSlug/dashboard/investigations/$investigationId': typeof DashboardInvestigationsInvestigationIdRoute
  '/$organizationSlug/dashboard/service/$serviceId': typeof DashboardServiceServiceIdRoute
  '/$organizationSlug/dashboard/trace/$traceId': typeof DashboardTraceTraceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$organizationSlug': typeof OrganizationSlugRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$organizationSlug/dashboard': typeof DashboardRouteWithChildren
  '/$organizationSlug/dashboard/detections': typeof DashboardDetectionsRoute
  '/$organizationSlug/dashboard/errors': typeof DashboardErrorsRoute
  '/$organizationSlug/dashboard/investigations': typeof DashboardInvestigationsRouteWithChildren
  '/$organizationSlug/dashboard/logs': typeof DashboardLogsRoute
  '/$organizationSlug/dashboard/services': typeof DashboardServicesRoute
  '/$organizationSlug/dashboard/settings': typeof DashboardSettingsRoute
  '/$organizationSlug/dashboard/traces': typeof DashboardTracesRoute
  '/$organizationSlug/dashboard/investigations/$investigationId': typeof DashboardInvestigationsInvestigationIdRoute
  '/$organizationSlug/dashboard/service/$serviceId': typeof DashboardServiceServiceIdRoute
  '/$organizationSlug/dashboard/trace/$traceId': typeof DashboardTraceTraceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$organizationSlug': typeof OrganizationSlugRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$organizationSlug/dashboard': typeof DashboardRouteWithChildren
  '/$organizationSlug/dashboard/': typeof DashboardIndexRoute
  '/$organizationSlug/dashboard/detections': typeof DashboardDetectionsRoute
  '/$organizationSlug/dashboard/errors': typeof DashboardErrorsRoute
  '/$organizationSlug/dashboard/investigations': typeof DashboardInvestigationsRouteWithChildren
  '/$organizationSlug/dashboard/logs': typeof DashboardLogsRoute
  '/$organizationSlug/dashboard/services': typeof DashboardServicesRoute
  '/$organizationSlug/dashboard/settings': typeof DashboardSettingsRoute
  '/$organizationSlug/dashboard/traces': typeof DashboardTracesRoute
  '/$organizationSlug/dashboard/investigations/$investigationId': typeof DashboardInvestigationsInvestigationIdRoute
  '/$organizationSlug/dashboard/service/$serviceId': typeof DashboardServiceServiceIdRoute
  '/$organizationSlug/dashboard/trace/$traceId': typeof DashboardTraceTraceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/register'
    | '/auth/callback'
    | '/$organizationSlug/dashboard'
    | '/$organizationSlug/dashboard/detections'
    | '/$organizationSlug/dashboard/errors'
    | '/$organizationSlug/dashboard/investigations'
    | '/$organizationSlug/dashboard/logs'
    | '/$organizationSlug/dashboard/services'
    | '/$organizationSlug/dashboard/settings'
    | '/$organizationSlug/dashboard/traces'
    | '/$organizationSlug/dashboard/'
    | '/$organizationSlug/dashboard/investigations/$investigationId'
    | '/$organizationSlug/dashboard/service/$serviceId'
    | '/$organizationSlug/dashboard/trace/$traceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/register'
    | '/auth/callback'
    | '/$organizationSlug/dashboard'
    | '/$organizationSlug/dashboard/detections'
    | '/$organizationSlug/dashboard/errors'
    | '/$organizationSlug/dashboard/investigations'
    | '/$organizationSlug/dashboard/logs'
    | '/$organizationSlug/dashboard/services'
    | '/$organizationSlug/dashboard/settings'
    | '/$organizationSlug/dashboard/traces'
    | '/$organizationSlug/dashboard/investigations/$investigationId'
    | '/$organizationSlug/dashboard/service/$serviceId'
    | '/$organizationSlug/dashboard/trace/$traceId'
  id:
    | '__root__'
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/register'
    | '/auth/callback'
    | '/$organizationSlug/dashboard'
    | '/$organizationSlug/dashboard/'
    | '/$organizationSlug/dashboard/detections'
    | '/$organizationSlug/dashboard/errors'
    | '/$organizationSlug/dashboard/investigations'
    | '/$organizationSlug/dashboard/logs'
    | '/$organizationSlug/dashboard/services'
    | '/$organizationSlug/dashboard/settings'
    | '/$organizationSlug/dashboard/traces'
    | '/$organizationSlug/dashboard/investigations/$investigationId'
    | '/$organizationSlug/dashboard/service/$serviceId'
    | '/$organizationSlug/dashboard/trace/$traceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationSlugRoute: typeof OrganizationSlugRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizationsRoute: typeof OrganizationsRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/$organizationSlug': { id: '/$organizationSlug'; path: '/$organizationSlug'; fullPath: '/$organizationSlug'; preLoaderRoute: typeof OrganizationSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding': { id: '/onboarding'; path: '/onboarding'; fullPath: '/onboarding'; preLoaderRoute: typeof OnboardingRouteImport; parentRoute: typeof rootRouteImport }
    '/organizations': { id: '/organizations'; path: '/organizations'; fullPath: '/organizations'; preLoaderRoute: typeof OrganizationsRouteImport; parentRoute: typeof rootRouteImport }
    '/register': { id: '/register'; path: '/register'; fullPath: '/register'; preLoaderRoute: typeof RegisterRouteImport; parentRoute: typeof rootRouteImport }
    '/auth/callback': { id: '/auth/callback'; path: '/auth/callback'; fullPath: '/auth/callback'; preLoaderRoute: typeof AuthCallbackRouteImport; parentRoute: typeof rootRouteImport }
    '/$organizationSlug/dashboard': { id: '/$organizationSlug/dashboard'; path: '/dashboard'; fullPath: '/$organizationSlug/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof OrganizationSlugRoute }
    '/$organizationSlug/dashboard/': { id: '/$organizationSlug/dashboard/'; path: '/'; fullPath: '/$organizationSlug/dashboard/'; preLoaderRoute: typeof OrganizationIndexRouteImport; parentRoute: typeof DashboardRoute }
    '/$organizationSlug/dashboard/detections': { id: '/$organizationSlug/dashboard/detections'; path: '/detections'; fullPath: '/$organizationSlug/dashboard/detections'; preLoaderRoute: typeof DetectionsRouteImport; parentRoute: typeof DashboardRoute }
    '/$organizationSlug/dashboard/errors': { id: '/$organizationSlug/dashboard/errors'; path: '/errors'; fullPath: '/$organizationSlug/dashboard/errors'; preLoaderRoute: typeof ErrorsRouteImport; parentRoute: typeof DashboardRoute }
    '/$organizationSlug/dashboard/investigations': { id: '/$organizationSlug/dashboard/investigations'; path: '/investigations'; fullPath: '/$organizationSlug/dashboard/investigations'; preLoaderRoute: typeof InvestigationsRouteImport; parentRoute: typeof DashboardRoute }
    '/$organizationSlug/dashboard/logs': { id: '/$organizationSlug/dashboard/logs'; path: '/logs'; fullPath: '/$organizationSlug/dashboard/logs'; preLoaderRoute: typeof LogsRouteImport; parentRoute: typeof DashboardRoute }
    '/$organizationSlug/dashboard/services': { id: '/$organizationSlug/dashboard/services'; path: '/services'; fullPath: '/$organizationSlug/dashboard/services'; preLoaderRoute: typeof ServicesRouteImport; parentRoute: typeof DashboardRoute }
    '/$organizationSlug/dashboard/settings': { id: '/$organizationSlug/dashboard/settings'; path: '/settings'; fullPath: '/$organizationSlug/dashboard/settings'; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof DashboardRoute }
    '/$organizationSlug/dashboard/traces': { id: '/$organizationSlug/dashboard/traces'; path: '/traces'; fullPath: '/$organizationSlug/dashboard/traces'; preLoaderRoute: typeof TracesRouteImport; parentRoute: typeof DashboardRoute }
    '/$organizationSlug/dashboard/investigations/$investigationId': { id: '/$organizationSlug/dashboard/investigations/$investigationId'; path: '/$investigationId'; fullPath: '/$organizationSlug/dashboard/investigations/$investigationId'; preLoaderRoute: typeof InvestigationDetailRouteImport; parentRoute: typeof DashboardInvestigationsRoute }
    '/$organizationSlug/dashboard/service/$serviceId': { id: '/$organizationSlug/dashboard/service/$serviceId'; path: '/service/$serviceId'; fullPath: '/$organizationSlug/dashboard/service/$serviceId'; preLoaderRoute: typeof ServiceDetailRouteImport; parentRoute: typeof DashboardRoute }
    '/$organizationSlug/dashboard/trace/$traceId': { id: '/$organizationSlug/dashboard/trace/$traceId'; path: '/trace/$traceId'; fullPath: '/$organizationSlug/dashboard/trace/$traceId'; preLoaderRoute: typeof TraceDetailRouteImport; parentRoute: typeof DashboardRoute }
  }
}

interface OrganizationSlugRouteChildren { DashboardRoute: typeof DashboardRouteWithChildren }
const OrganizationSlugRouteChildren: OrganizationSlugRouteChildren = { DashboardRoute: DashboardRouteWithChildren }
const OrganizationSlugRouteWithChildren = OrganizationSlugRoute._addFileChildren(OrganizationSlugRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDetectionsRoute: typeof DashboardDetectionsRoute
  DashboardErrorsRoute: typeof DashboardErrorsRoute
  DashboardInvestigationsRoute: typeof DashboardInvestigationsRouteWithChildren
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTracesRoute: typeof DashboardTracesRoute
  DashboardServiceServiceIdRoute: typeof DashboardServiceServiceIdRoute
  DashboardTraceTraceIdRoute: typeof DashboardTraceTraceIdRoute
}
const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute,
  DashboardDetectionsRoute,
  DashboardErrorsRoute,
  DashboardInvestigationsRoute: DashboardInvestigationsRouteWithChildren,
  DashboardLogsRoute,
  DashboardServicesRoute,
  DashboardSettingsRoute,
  DashboardTracesRoute,
  DashboardServiceServiceIdRoute,
  DashboardTraceTraceIdRoute,
}
const DashboardRouteWithChildren = DashboardRoute._addFileChildren(DashboardRouteChildren)

interface DashboardInvestigationsRouteChildren { DashboardInvestigationsInvestigationIdRoute: typeof DashboardInvestigationsInvestigationIdRoute }
const DashboardInvestigationsRouteChildren: DashboardInvestigationsRouteChildren = { DashboardInvestigationsInvestigationIdRoute }
const DashboardInvestigationsRouteWithChildren = DashboardInvestigationsRoute._addFileChildren(DashboardInvestigationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  OrganizationSlugRoute: OrganizationSlugRouteWithChildren,
  LoginRoute,
  OnboardingRoute,
  OrganizationsRoute,
  RegisterRoute,
  AuthCallbackRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
