/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationSlugRouteImport } from './routes/$organizationSlug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrganizationSlugIndexRouteImport } from './routes/$organizationSlug/index'
import { Route as OrganizationSlugAiRouteImport } from './routes/$organizationSlug/ai'
import { Route as OrganizationSlugApiKeysRouteImport } from './routes/$organizationSlug/api-keys'
import { Route as OrganizationSlugDashboardRouteImport } from './routes/$organizationSlug/dashboard'
import { Route as OrganizationSlugDeploymentsRouteImport } from './routes/$organizationSlug/deployments'
import { Route as OrganizationSlugDetectionsRouteImport } from './routes/$organizationSlug/detections'
import { Route as OrganizationSlugErrorsRouteImport } from './routes/$organizationSlug/errors'
import { Route as OrganizationSlugInvestigationsRouteImport } from './routes/$organizationSlug/investigations'
import { Route as OrganizationSlugLogsRouteImport } from './routes/$organizationSlug/logs'
import { Route as OrganizationSlugOperationsRouteImport } from './routes/$organizationSlug/operations'
import { Route as OrganizationSlugServiceMapRouteImport } from './routes/$organizationSlug/service-map'
import { Route as OrganizationSlugServicesRouteImport } from './routes/$organizationSlug/services'
import { Route as OrganizationSlugSettingsRouteImport } from './routes/$organizationSlug/settings'
import { Route as OrganizationSlugTracesRouteImport } from './routes/$organizationSlug/traces'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as OrganizationSlugInvestigationsInvestigationIdRouteImport } from './routes/$organizationSlug/investigations.$investigationId'
import { Route as OrganizationSlugServiceServiceIdRouteImport } from './routes/$organizationSlug/service.$serviceId'
import { Route as OrganizationSlugTraceTraceIdRouteImport } from './routes/$organizationSlug/trace.$traceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugRoute = OrganizationSlugRouteImport.update({
  id: '/$organizationSlug',
  path: '/$organizationSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugIndexRoute = OrganizationSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationSlugRoute,
} as any)
const OrganizationSlugAiRoute = OrganizationSlugAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => OrganizationSlugRoute,
} as any)
const OrganizationSlugApiKeysRoute = OrganizationSlugApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => OrganizationSlugRoute,
} as any)
const OrganizationSlugDashboardRoute =
  OrganizationSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)
const OrganizationSlugDeploymentsRoute =
  OrganizationSlugDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)
const OrganizationSlugDetectionsRoute =
  OrganizationSlugDetectionsRouteImport.update({
    id: '/detections',
    path: '/detections',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)
const OrganizationSlugErrorsRoute = OrganizationSlugErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => OrganizationSlugRoute,
} as any)
const OrganizationSlugInvestigationsRoute =
  OrganizationSlugInvestigationsRouteImport.update({
    id: '/investigations',
    path: '/investigations',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)
const OrganizationSlugLogsRoute = OrganizationSlugLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => OrganizationSlugRoute,
} as any)
const OrganizationSlugOperationsRoute =
  OrganizationSlugOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)
const OrganizationSlugServiceMapRoute =
  OrganizationSlugServiceMapRouteImport.update({
    id: '/service-map',
    path: '/service-map',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)
const OrganizationSlugServicesRoute =
  OrganizationSlugServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)
const OrganizationSlugSettingsRoute =
  OrganizationSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)
const OrganizationSlugTracesRoute = OrganizationSlugTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => OrganizationSlugRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSlugInvestigationsInvestigationIdRoute =
  OrganizationSlugInvestigationsInvestigationIdRouteImport.update({
    id: '/$investigationId',
    path: '/$investigationId',
    getParentRoute: () => OrganizationSlugInvestigationsRoute,
  } as any)
const OrganizationSlugServiceServiceIdRoute =
  OrganizationSlugServiceServiceIdRouteImport.update({
    id: '/service/$serviceId',
    path: '/service/$serviceId',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)
const OrganizationSlugTraceTraceIdRoute =
  OrganizationSlugTraceTraceIdRouteImport.update({
    id: '/trace/$traceId',
    path: '/trace/$traceId',
    getParentRoute: () => OrganizationSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$organizationSlug': typeof OrganizationSlugRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/$organizationSlug/ai': typeof OrganizationSlugAiRoute
  '/$organizationSlug/api-keys': typeof OrganizationSlugApiKeysRoute
  '/$organizationSlug/dashboard': typeof OrganizationSlugDashboardRoute
  '/$organizationSlug/deployments': typeof OrganizationSlugDeploymentsRoute
  '/$organizationSlug/detections': typeof OrganizationSlugDetectionsRoute
  '/$organizationSlug/errors': typeof OrganizationSlugErrorsRoute
  '/$organizationSlug/investigations': typeof OrganizationSlugInvestigationsRouteWithChildren
  '/$organizationSlug/logs': typeof OrganizationSlugLogsRoute
  '/$organizationSlug/operations': typeof OrganizationSlugOperationsRoute
  '/$organizationSlug/service-map': typeof OrganizationSlugServiceMapRoute
  '/$organizationSlug/services': typeof OrganizationSlugServicesRoute
  '/$organizationSlug/settings': typeof OrganizationSlugSettingsRoute
  '/$organizationSlug/traces': typeof OrganizationSlugTracesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$organizationSlug/': typeof OrganizationSlugIndexRoute
  '/$organizationSlug/investigations/$investigationId': typeof OrganizationSlugInvestigationsInvestigationIdRoute
  '/$organizationSlug/service/$serviceId': typeof OrganizationSlugServiceServiceIdRoute
  '/$organizationSlug/trace/$traceId': typeof OrganizationSlugTraceTraceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/$organizationSlug/ai': typeof OrganizationSlugAiRoute
  '/$organizationSlug/api-keys': typeof OrganizationSlugApiKeysRoute
  '/$organizationSlug/dashboard': typeof OrganizationSlugDashboardRoute
  '/$organizationSlug/deployments': typeof OrganizationSlugDeploymentsRoute
  '/$organizationSlug/detections': typeof OrganizationSlugDetectionsRoute
  '/$organizationSlug/errors': typeof OrganizationSlugErrorsRoute
  '/$organizationSlug/investigations': typeof OrganizationSlugInvestigationsRouteWithChildren
  '/$organizationSlug/logs': typeof OrganizationSlugLogsRoute
  '/$organizationSlug/operations': typeof OrganizationSlugOperationsRoute
  '/$organizationSlug/service-map': typeof OrganizationSlugServiceMapRoute
  '/$organizationSlug/services': typeof OrganizationSlugServicesRoute
  '/$organizationSlug/settings': typeof OrganizationSlugSettingsRoute
  '/$organizationSlug/traces': typeof OrganizationSlugTracesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$organizationSlug': typeof OrganizationSlugIndexRoute
  '/$organizationSlug/investigations/$investigationId': typeof OrganizationSlugInvestigationsInvestigationIdRoute
  '/$organizationSlug/service/$serviceId': typeof OrganizationSlugServiceServiceIdRoute
  '/$organizationSlug/trace/$traceId': typeof OrganizationSlugTraceTraceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$organizationSlug': typeof OrganizationSlugRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/$organizationSlug/ai': typeof OrganizationSlugAiRoute
  '/$organizationSlug/api-keys': typeof OrganizationSlugApiKeysRoute
  '/$organizationSlug/dashboard': typeof OrganizationSlugDashboardRoute
  '/$organizationSlug/deployments': typeof OrganizationSlugDeploymentsRoute
  '/$organizationSlug/detections': typeof OrganizationSlugDetectionsRoute
  '/$organizationSlug/errors': typeof OrganizationSlugErrorsRoute
  '/$organizationSlug/investigations': typeof OrganizationSlugInvestigationsRouteWithChildren
  '/$organizationSlug/logs': typeof OrganizationSlugLogsRoute
  '/$organizationSlug/operations': typeof OrganizationSlugOperationsRoute
  '/$organizationSlug/service-map': typeof OrganizationSlugServiceMapRoute
  '/$organizationSlug/services': typeof OrganizationSlugServicesRoute
  '/$organizationSlug/settings': typeof OrganizationSlugSettingsRoute
  '/$organizationSlug/traces': typeof OrganizationSlugTracesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$organizationSlug/': typeof OrganizationSlugIndexRoute
  '/$organizationSlug/investigations/$investigationId': typeof OrganizationSlugInvestigationsInvestigationIdRoute
  '/$organizationSlug/service/$serviceId': typeof OrganizationSlugServiceServiceIdRoute
  '/$organizationSlug/trace/$traceId': typeof OrganizationSlugTraceTraceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/register'
    | '/$organizationSlug/ai'
    | '/$organizationSlug/api-keys'
    | '/$organizationSlug/dashboard'
    | '/$organizationSlug/deployments'
    | '/$organizationSlug/detections'
    | '/$organizationSlug/errors'
    | '/$organizationSlug/investigations'
    | '/$organizationSlug/logs'
    | '/$organizationSlug/operations'
    | '/$organizationSlug/service-map'
    | '/$organizationSlug/services'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/traces'
    | '/auth/callback'
    | '/$organizationSlug/'
    | '/$organizationSlug/investigations/$investigationId'
    | '/$organizationSlug/service/$serviceId'
    | '/$organizationSlug/trace/$traceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/register'
    | '/$organizationSlug/ai'
    | '/$organizationSlug/api-keys'
    | '/$organizationSlug/dashboard'
    | '/$organizationSlug/deployments'
    | '/$organizationSlug/detections'
    | '/$organizationSlug/errors'
    | '/$organizationSlug/investigations'
    | '/$organizationSlug/logs'
    | '/$organizationSlug/operations'
    | '/$organizationSlug/service-map'
    | '/$organizationSlug/services'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/traces'
    | '/auth/callback'
    | '/$organizationSlug'
    | '/$organizationSlug/investigations/$investigationId'
    | '/$organizationSlug/service/$serviceId'
    | '/$organizationSlug/trace/$traceId'
  id:
    | '__root__'
    | '/'
    | '/$organizationSlug'
    | '/login'
    | '/onboarding'
    | '/organizations'
    | '/register'
    | '/$organizationSlug/ai'
    | '/$organizationSlug/api-keys'
    | '/$organizationSlug/dashboard'
    | '/$organizationSlug/deployments'
    | '/$organizationSlug/detections'
    | '/$organizationSlug/errors'
    | '/$organizationSlug/investigations'
    | '/$organizationSlug/logs'
    | '/$organizationSlug/operations'
    | '/$organizationSlug/service-map'
    | '/$organizationSlug/services'
    | '/$organizationSlug/settings'
    | '/$organizationSlug/traces'
    | '/auth/callback'
    | '/$organizationSlug/'
    | '/$organizationSlug/investigations/$investigationId'
    | '/$organizationSlug/service/$serviceId'
    | '/$organizationSlug/trace/$traceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationSlugRoute: typeof OrganizationSlugRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizationsRoute: typeof OrganizationsRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug': {
      id: '/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof OrganizationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug/': {
      id: '/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof OrganizationSlugIndexRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/ai': {
      id: '/$organizationSlug/ai'
      path: '/ai'
      fullPath: '/$organizationSlug/ai'
      preLoaderRoute: typeof OrganizationSlugAiRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/api-keys': {
      id: '/$organizationSlug/api-keys'
      path: '/api-keys'
      fullPath: '/$organizationSlug/api-keys'
      preLoaderRoute: typeof OrganizationSlugApiKeysRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/dashboard': {
      id: '/$organizationSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$organizationSlug/dashboard'
      preLoaderRoute: typeof OrganizationSlugDashboardRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/deployments': {
      id: '/$organizationSlug/deployments'
      path: '/deployments'
      fullPath: '/$organizationSlug/deployments'
      preLoaderRoute: typeof OrganizationSlugDeploymentsRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/detections': {
      id: '/$organizationSlug/detections'
      path: '/detections'
      fullPath: '/$organizationSlug/detections'
      preLoaderRoute: typeof OrganizationSlugDetectionsRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/errors': {
      id: '/$organizationSlug/errors'
      path: '/errors'
      fullPath: '/$organizationSlug/errors'
      preLoaderRoute: typeof OrganizationSlugErrorsRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/investigations': {
      id: '/$organizationSlug/investigations'
      path: '/investigations'
      fullPath: '/$organizationSlug/investigations'
      preLoaderRoute: typeof OrganizationSlugInvestigationsRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/logs': {
      id: '/$organizationSlug/logs'
      path: '/logs'
      fullPath: '/$organizationSlug/logs'
      preLoaderRoute: typeof OrganizationSlugLogsRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/operations': {
      id: '/$organizationSlug/operations'
      path: '/operations'
      fullPath: '/$organizationSlug/operations'
      preLoaderRoute: typeof OrganizationSlugOperationsRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/service-map': {
      id: '/$organizationSlug/service-map'
      path: '/service-map'
      fullPath: '/$organizationSlug/service-map'
      preLoaderRoute: typeof OrganizationSlugServiceMapRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/services': {
      id: '/$organizationSlug/services'
      path: '/services'
      fullPath: '/$organizationSlug/services'
      preLoaderRoute: typeof OrganizationSlugServicesRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/settings': {
      id: '/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/$organizationSlug/settings'
      preLoaderRoute: typeof OrganizationSlugSettingsRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/traces': {
      id: '/$organizationSlug/traces'
      path: '/traces'
      fullPath: '/$organizationSlug/traces'
      preLoaderRoute: typeof OrganizationSlugTracesRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$organizationSlug/investigations/$investigationId': {
      id: '/$organizationSlug/investigations/$investigationId'
      path: '/$investigationId'
      fullPath: '/$organizationSlug/investigations/$investigationId'
      preLoaderRoute: typeof OrganizationSlugInvestigationsInvestigationIdRouteImport
      parentRoute: typeof OrganizationSlugInvestigationsRoute
    }
    '/$organizationSlug/service/$serviceId': {
      id: '/$organizationSlug/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/$organizationSlug/service/$serviceId'
      preLoaderRoute: typeof OrganizationSlugServiceServiceIdRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
    '/$organizationSlug/trace/$traceId': {
      id: '/$organizationSlug/trace/$traceId'
      path: '/trace/$traceId'
      fullPath: '/$organizationSlug/trace/$traceId'
      preLoaderRoute: typeof OrganizationSlugTraceTraceIdRouteImport
      parentRoute: typeof OrganizationSlugRoute
    }
  }
}

interface OrganizationSlugInvestigationsRouteChildren {
  OrganizationSlugInvestigationsInvestigationIdRoute: typeof OrganizationSlugInvestigationsInvestigationIdRoute
}

const OrganizationSlugInvestigationsRouteChildren: OrganizationSlugInvestigationsRouteChildren =
  {
    OrganizationSlugInvestigationsInvestigationIdRoute:
      OrganizationSlugInvestigationsInvestigationIdRoute,
  }

const OrganizationSlugInvestigationsRouteWithChildren =
  OrganizationSlugInvestigationsRoute._addFileChildren(
    OrganizationSlugInvestigationsRouteChildren,
  )

interface OrganizationSlugRouteChildren {
  OrganizationSlugAiRoute: typeof OrganizationSlugAiRoute
  OrganizationSlugApiKeysRoute: typeof OrganizationSlugApiKeysRoute
  OrganizationSlugDashboardRoute: typeof OrganizationSlugDashboardRoute
  OrganizationSlugDeploymentsRoute: typeof OrganizationSlugDeploymentsRoute
  OrganizationSlugDetectionsRoute: typeof OrganizationSlugDetectionsRoute
  OrganizationSlugErrorsRoute: typeof OrganizationSlugErrorsRoute
  OrganizationSlugInvestigationsRoute: typeof OrganizationSlugInvestigationsRouteWithChildren
  OrganizationSlugLogsRoute: typeof OrganizationSlugLogsRoute
  OrganizationSlugOperationsRoute: typeof OrganizationSlugOperationsRoute
  OrganizationSlugServiceMapRoute: typeof OrganizationSlugServiceMapRoute
  OrganizationSlugServicesRoute: typeof OrganizationSlugServicesRoute
  OrganizationSlugSettingsRoute: typeof OrganizationSlugSettingsRoute
  OrganizationSlugTracesRoute: typeof OrganizationSlugTracesRoute
  OrganizationSlugIndexRoute: typeof OrganizationSlugIndexRoute
  OrganizationSlugServiceServiceIdRoute: typeof OrganizationSlugServiceServiceIdRoute
  OrganizationSlugTraceTraceIdRoute: typeof OrganizationSlugTraceTraceIdRoute
}

const OrganizationSlugRouteChildren: OrganizationSlugRouteChildren = {
  OrganizationSlugAiRoute: OrganizationSlugAiRoute,
  OrganizationSlugApiKeysRoute: OrganizationSlugApiKeysRoute,
  OrganizationSlugDashboardRoute: OrganizationSlugDashboardRoute,
  OrganizationSlugDeploymentsRoute: OrganizationSlugDeploymentsRoute,
  OrganizationSlugDetectionsRoute: OrganizationSlugDetectionsRoute,
  OrganizationSlugErrorsRoute: OrganizationSlugErrorsRoute,
  OrganizationSlugInvestigationsRoute:
    OrganizationSlugInvestigationsRouteWithChildren,
  OrganizationSlugLogsRoute: OrganizationSlugLogsRoute,
  OrganizationSlugOperationsRoute: OrganizationSlugOperationsRoute,
  OrganizationSlugServiceMapRoute: OrganizationSlugServiceMapRoute,
  OrganizationSlugServicesRoute: OrganizationSlugServicesRoute,
  OrganizationSlugSettingsRoute: OrganizationSlugSettingsRoute,
  OrganizationSlugTracesRoute: OrganizationSlugTracesRoute,
  OrganizationSlugIndexRoute: OrganizationSlugIndexRoute,
  OrganizationSlugServiceServiceIdRoute: OrganizationSlugServiceServiceIdRoute,
  OrganizationSlugTraceTraceIdRoute: OrganizationSlugTraceTraceIdRoute,
}

const OrganizationSlugRouteWithChildren =
  OrganizationSlugRoute._addFileChildren(OrganizationSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationSlugRoute: OrganizationSlugRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrganizationsRoute: OrganizationsRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
