import { createFileRoute, Link } from '@tanstack/react-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BrainCircuit, RefreshCw, AlertTriangle, Clock, ChevronRight, ShieldCheck, FileSearch } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '~/components/ui/card';
import { Button } from '~/components/ui/button';
import { Badge } from '~/components/ui/badge';
import { Skeleton } from '~/components/ui/skeleton';
import { api } from '~/lib/api';
import { QueryErrorState } from '~/components/query-error-state';
import { useProject } from '~/lib/project-context';
import { useState } from 'react';

export const Route = createFileRoute('/dashboard/detections')({ component: DetectionOverview });
type FindingType = 'latency' | 'error_rate' | 'throughput' | 'dependency_latency' | 'trace_span' | 'bottleneck';
type Severity = 'warning' | 'critical';
interface DetectionFinding { id: string; projectId: string; serviceName: string; type: FindingType; severity: Severity; title: string; description: string; observedValue: number; threshold: number; unit: string; window: { start: string; end: string }; evidence: Array<{ kind: string; label: string; value: number | string; context?: Record<string, unknown> }>; }
interface RcaAnalysis { id: string; serviceName: string; severity: Severity; summary: string; rootCause: string; contributingFactors: string[]; investigationSteps: string[]; suggestedChanges: string[]; evidenceRefs: string[]; confidence: 'low' | 'medium' | 'high'; limitations: string[]; provider: string; model: string; promptVersion: string; createdAt: string; }

function DetectionOverview() {
  const { projectId } = useProject(); const queryClient = useQueryClient(); const [selectedId, setSelectedId] = useState<string | null>(null);
  const { data: findings, isLoading, isError, refetch } = useQuery({ queryKey: ['detections', projectId], queryFn: () => api.get<DetectionFinding[]>(`/projects/${projectId}/detections`), enabled: !!projectId });
  const selected = findings?.find((item) => item.id === selectedId) ?? findings?.[0]; const isBottleneck = selected?.type === 'bottleneck';
  const { data: rca, isLoading: rcaLoading } = useQuery({ queryKey: ['rca', projectId, selected?.id], queryFn: () => api.get<RcaAnalysis>(`/projects/${projectId}/findings/${selected?.id}/rca`), enabled: !!projectId && !!selected?.id && isBottleneck, retry: false });
  const { data: history } = useQuery({ queryKey: ['rca-history', projectId, selected?.id], queryFn: () => api.get<RcaAnalysis[]>(`/projects/${projectId}/findings/${selected?.id}/rca/history`), enabled: !!projectId && !!selected?.id && isBottleneck });
  const generate = useMutation({ mutationFn: (regenerate: boolean) => api.post<RcaAnalysis>(`/projects/${projectId}/findings/${selected?.id}/rca`, { regenerate }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['rca', projectId, selected?.id] }); void queryClient.invalidateQueries({ queryKey: ['rca-history', projectId, selected?.id] }); } });
  if (!projectId) return <EmptyProject />;
  if (isError) return <QueryErrorState onRetry={() => void refetch()} />;
  return <div className="mx-auto max-w-[1440px] space-y-6 pb-10">
    <header><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#16931F]">Intelligent analysis</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Detections</h1><p className="mt-1 text-sm text-muted-foreground">Find bottlenecks from telemetry evidence, then inspect the reasoning behind each finding.</p></header>
    {isLoading ? <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><Skeleton className="h-[600px]" /><Skeleton className="h-[600px]" /></div> : !findings?.length ? <Card><CardContent className="p-12 text-center"><FileSearch className="mx-auto h-8 w-8 text-[#16931F]" /><p className="mt-3 font-medium">No detections yet</p><p className="mt-1 text-sm text-muted-foreground">Detections need real request telemetry before the pipeline can produce evidence-backed findings.</p><Link to="/onboarding" className="mt-4 inline-flex text-sm font-medium text-[#16931F] hover:underline">Open setup flow</Link></CardContent></Card> : <div className="grid gap-4 lg:grid-cols-[360px_1fr]">
      <Card className="overflow-hidden border-[#DBE5D7] bg-white shadow-none"><CardHeader className="border-b bg-[#F7FAF4]"><CardTitle className="text-base">Findings</CardTitle><CardDescription>{findings.length} recent finding{findings.length === 1 ? '' : 's'}</CardDescription></CardHeader><CardContent className="p-0"><div className="divide-y divide-[#DBE5D7]">{findings.map((finding) => <button key={finding.id} type="button" onClick={() => setSelectedId(finding.id)} className={`w-full p-4 text-left transition-colors hover:bg-[#F7FAF4] focus-visible:bg-[#F7FAF4] ${selected?.id === finding.id ? 'bg-[#C9E7EB]' : ''}`}><div className="flex items-start gap-3"><SeverityIcon severity={finding.severity} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{finding.title}</p><div className="mt-1 flex flex-wrap gap-x-2 text-xs text-muted-foreground"><span>{finding.serviceName}</span><span>·</span><span>{finding.type}</span></div><p className="mt-1 font-mono text-[11px] text-muted-foreground">{new Date(finding.window.end).toLocaleString()}</p></div><ChevronRight className="mt-1 h-4 w-4 shrink-0 text-muted-foreground" /></div></button>)}</div></CardContent></Card>
      {selected && <Card className="border-[#DBE5D7] bg-white shadow-none"><CardHeader className="border-b"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><CardTitle className="text-lg">{selected.title}</CardTitle><Badge variant="outline" className={selected.severity === 'critical' ? 'border-[#F8C7C2] bg-[#FDE8E6] text-[#8A1C13]' : 'border-[#FDE68A] bg-[#FEF3C7] text-[#713F12]'}>{selected.severity}</Badge></div><CardDescription className="mt-2">{selected.serviceName} · observed {selected.observedValue}{selected.unit} · threshold {selected.threshold}{selected.unit}</CardDescription></div>{isBottleneck && <Button size="sm" variant="outline" onClick={() => generate.mutate(true)} disabled={generate.isPending} className="border-[#CBD8C7]"><RefreshCw className={generate.isPending ? 'mr-2 h-3.5 w-3.5 animate-spin' : 'mr-2 h-3.5 w-3.5'} />Regenerate RCA</Button>}</div></CardHeader>
        <CardContent className="space-y-7 p-5 md:p-6"><section><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#16931F]" /><h2 className="text-sm font-semibold">Detection evidence</h2></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{selected.description}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{selected.evidence.map((item, index) => <div key={`${item.label}-${index}`} className="rounded-lg border border-[#DBE5D7] bg-[#F7FAF4] p-4"><p className="text-[11px] uppercase tracking-wide text-muted-foreground">{item.label}</p><p className="mt-1 break-words font-mono text-sm font-medium">{String(item.value)}</p></div>)}</div></section>
        {isBottleneck && <section className="border-t border-[#DBE5D7] pt-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><BrainCircuit className="h-4 w-4 text-[#16931F]" /><h2 className="text-sm font-semibold">AI root-cause analysis</h2></div><p className="mt-1 text-xs text-muted-foreground">Generated from deterministic evidence. Inspect confidence and limitations before acting.</p></div>{!rca && !rcaLoading && <Button onClick={() => generate.mutate(false)} disabled={generate.isPending} className="bg-[#8BD125] text-[#182012] hover:bg-[#8BD125]/90"><BrainCircuit className="mr-2 h-4 w-4" />Generate RCA</Button>}</div>{rcaLoading ? <div className="mt-5 space-y-3"><Skeleton className="h-24" /><Skeleton className="h-32" /></div> : rca ? <RcaContent rca={rca} history={history ?? []} /> : <div className="mt-5 rounded-lg border border-dashed border-[#CBD8C7] bg-[#F7FAF4] p-6 text-sm text-muted-foreground">No RCA has been generated for this finding.</div>}{generate.isError && <p className="mt-3 text-sm text-[#8A1C13]">{generate.error instanceof Error ? generate.error.message : 'RCA generation failed.'}</p>}</section>}</CardContent>
      </Card>}
    </div>}
  </div>;
}
function RcaContent({ rca, history }: { rca: RcaAnalysis; history: RcaAnalysis[] }) { return <div className="mt-5 space-y-5"><div className="rounded-lg border border-[#DBE5D7] bg-[#C9E7EB] p-4"><div className="flex flex-wrap gap-3 text-xs text-[#182012]/70"><span>Confidence: <strong className="text-[#182012]">{rca.confidence}</strong></span><span>Model: {rca.model}</span><span>Prompt: {rca.promptVersion}</span><span>{new Date(rca.createdAt).toLocaleString()}</span></div><p className="mt-3 text-sm leading-6 text-[#182012]">{rca.summary}</p></div><RcaList title="Root cause" items={[rca.rootCause]} /><RcaList title="Contributing factors" items={rca.contributingFactors} /><RcaList title="Investigation steps" items={rca.investigationSteps} /><RcaList title="Suggested changes" items={rca.suggestedChanges} /><RcaList title="Limitations" items={rca.limitations} />{history.length > 1 && <p className="text-xs text-muted-foreground">RCA history: {history.length} analyses for this finding.</p>}</div>; }
function RcaList({ title, items }: { title: string; items: string[] }) { if (!items.length) return null; return <div><h3 className="text-sm font-semibold">{title}</h3><ul className="mt-2 space-y-2 text-sm leading-6 text-muted-foreground">{items.map((item, index) => <li key={`${title}-${index}`} className="border-l-2 border-[#8BD125] pl-3">{item}</li>)}</ul></div>; }
function SeverityIcon({ severity }: { severity: Severity }) { return severity === 'critical' ? <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-[#8A1C13]" aria-label="Critical" /> : <Clock className="mt-0.5 h-4 w-4 shrink-0 text-[#713F12]" aria-label="Warning" />; }
function EmptyProject() { return <Card><CardContent className="p-10 text-center"><p className="font-medium">Choose a project</p><p className="mt-1 text-sm text-muted-foreground">Select a project from the top bar to inspect detections.</p></CardContent></Card>; }
