import { createFileRoute, Link } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { Activity, AlertTriangle, ArrowUpRight, BrainCircuit, GitBranch, GitCommitHorizontal, Search, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card';
import { Input } from '~/components/ui/input';
import { Badge } from '~/components/ui/badge';
import { Skeleton } from '~/components/ui/skeleton';
import { api } from '~/lib/api';
import { QueryErrorState } from '~/components/query-error-state';
import { useProject } from '~/lib/project-context';

export const Route = createFileRoute('/dashboard/investigations')({ component: Investigations });
type EventKind='detection'|'trace'|'error'|'deployment'|'log';
interface InvestigationEvent{id:string;kind:EventKind;title:string;description?:string;timestamp:string;service?:string;severity?:string;sourceId?:string;metadata?:Record<string,string|number>}
interface Investigation{ id:string;title:string;status:string;summary:string;startedAt:string;updatedAt:string;service?:string;events:InvestigationEvent[];evidence:Array<{label:string;value:string;sourceId?:string}>;changes:Array<{id:string;message:string;author?:string;timestamp:string;service?:string}> }
function Investigations(){const{projectId}=useProject();const[q,setQ]=useState('');const{data,isLoading,isError,refetch}=useQuery({queryKey:['investigations',projectId,q],queryFn:()=>api.get<Investigation[]>(`/projects/${projectId}/investigations${q?`?q=${encodeURIComponent(q)}`:''}`),enabled:!!projectId});if(isError)return <QueryErrorState onRetry={() => void refetch()} />;if(!projectId)return <Card><CardContent className="p-12 text-center">Choose a project</CardContent></Card>;return <div className="mx-auto max-w-[1440px] space-y-6 pb-10"><header><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#16931F]">Intelligent investigation</p><h1 className="mt-1 text-2xl font-semibold">Investigations</h1><p className="mt-1 text-sm text-muted-foreground">Connect detections, traces, errors, logs and changes into one evidence timeline.</p></header><Card className="border-[#DBE5D7] shadow-none"><CardContent className="p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search investigations, services or evidence" className="pl-9 bg-[#F7FAF4]"/></div></CardContent></Card>{isLoading?<div className="grid gap-4 lg:grid-cols-[380px_1fr]"><Skeleton className="h-[620px]"/><Skeleton className="h-[620px]"/></div>:!data?.length?<Card><CardContent className="p-12 text-center"><BrainCircuit className="mx-auto h-8 w-8 text-[#16931F]"/><p className="mt-3 font-medium">No investigations yet</p><p className="mt-1 text-sm text-muted-foreground">Evidence-linked investigations will appear here when findings are correlated.</p></CardContent></Card>:<div className="grid gap-4 lg:grid-cols-[380px_1fr]"> <Card className="overflow-hidden border-[#DBE5D7] shadow-none"><CardHeader className="border-b bg-[#F7FAF4]"><CardTitle className="text-base">Cases</CardTitle></CardHeader><CardContent className="p-0 divide-y divide-[#DBE5D7]">{data.map(item=><Link key={item.id} to="/dashboard/investigations/$investigationId" params={{investigationId:item.id}} className="block p-4 hover:bg-[#F7FAF4]"><div className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#C9E7EB]"><ShieldCheck className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{item.title}</p><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{item.summary}</p><div className="mt-2 flex gap-2"><Badge variant="outline">{item.status}</Badge>{item.service&&<span className="text-xs text-muted-foreground">{item.service}</span>}</div></div><ArrowUpRight className="h-4 w-4 text-muted-foreground"/></div></Link>)}</CardContent></Card><InvestigationPreview item={data[0]}/></div>}</div>}
function InvestigationPreview({item}:{item:Investigation}){return <Card className="border-[#DBE5D7] shadow-none"><CardHeader className="border-b"><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-lg">{item.title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{item.summary}</p></div><Badge variant="outline">{item.events.length} signals</Badge></div></CardHeader><CardContent className="p-5 md:p-6 space-y-7"><section><div className="flex items-center gap-2"><Activity className="h-4 w-4 text-[#16931F]"/><h2 className="text-sm font-semibold">Evidence timeline</h2></div><div className="mt-4 space-y-0">{item.events.slice(0,8).map((event,index)=><div key={event.id} className="relative flex gap-4 pb-5"><div className="flex w-4 flex-col items-center"><span className="z-10 mt-1 h-2.5 w-2.5 rounded-full bg-[#8BD125] ring-4 ring-[#F7FAF4]"/>{index<Math.min(item.events.length,8)-1&&<span className="absolute top-4 bottom-0 w-px bg-[#C9D8C5]"/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-medium">{event.title}</span><Badge variant="outline">{event.kind}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{event.description}</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">{new Date(event.timestamp).toLocaleString()}{event.service?` · ${event.service}`:''}</p></div></div>)}</div></section><section className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border bg-[#F7FAF4] p-4"><h3 className="text-sm font-semibold">Evidence graph</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.evidence.length} linked evidence nodes across the investigation.</p><div className="mt-4 space-y-2">{item.evidence.slice(0,5).map(e=><div key={e.label} className="flex items-center gap-2 text-xs"><span className="h-2 w-2 rounded-full bg-[#16931F]"/><span className="font-medium">{e.label}</span><span className="truncate text-muted-foreground">{e.value}</span></div>)}</div></div><div className="rounded-xl border bg-[#C9E7EB] p-4"><h3 className="text-sm font-semibold">Change context</h3><p className="mt-1 text-xs leading-5 text-[#182012]/70">Recent deployments and source changes are kept alongside telemetry to test temporal correlation.</p><div className="mt-4 space-y-2">{item.changes.slice(0,4).map(change=><div key={change.id} className="flex gap-2 text-xs"><GitCommitHorizontal className="h-3.5 w-3.5 shrink-0"/><span className="truncate font-mono">{change.message}</span></div>)}</div></div></section></CardContent></Card>}
