import { createFileRoute, Link } from '@tanstack/react-router';
import { useQuery } from '@tanstack/react-query';
import { Search, GitBranch, Clock3, ChevronRight } from 'lucide-react';
import { useState } from 'react';
import { Card, CardContent } from '~/components/ui/card';
import { Input } from '~/components/ui/input';
import { Skeleton } from '~/components/ui/skeleton';
import { Badge } from '~/components/ui/badge';
import { api } from '~/lib/api';
import { QueryErrorState } from '~/components/query-error-state';
import { useProject } from '~/lib/project-context';

export const Route = createFileRoute('/dashboard/traces')({ component: TraceExplorer });
interface Trace { traceId:string; rootService:string; rootOperation:string; durationMs:number; spanCount:number; status:string; startTime:string; }
function TraceExplorer(){const {projectId}=useProject();const [q,setQ]=useState('');const {data,isLoading,isError,refetch}=useQuery({queryKey:['traces',projectId,q],queryFn:()=>api.get<Trace[]>(`/traces?projectId=${projectId}${q?`&q=${encodeURIComponent(q)}`:''}`),enabled:!!projectId});if(!projectId)return <Empty/>;if(isError)return <QueryErrorState onRetry={() => void refetch()} />;return <div className="mx-auto w-full space-y-6 pb-10"><header><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#16931F]">Distributed telemetry</p><h1 className="mt-1 text-2xl font-semibold">Traces</h1><p className="mt-1 text-sm text-muted-foreground">Follow a request across services and inspect its critical path.</p></header><Card className="border-border shadow-none"><CardContent className="p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search trace ID, service, or operation" className="bg-muted pl-9" aria-label="Search traces"/></div></CardContent></Card><Card className="overflow-hidden border-border shadow-none"><CardContent className="p-0">{isLoading?<div className="space-y-2 p-4">{Array.from({length:7}).map((_,i)=><Skeleton key={i} className="h-14"/>)}</div>:!data?.length?<div className="p-12 text-center"><GitBranch className="mx-auto h-8 w-8 text-[#16931F]"/><p className="mt-3 font-medium">{q ? 'No traces found' : 'Waiting for your first trace'}</p><p className="mt-1 text-sm text-muted-foreground">{q ? 'Try a broader search or another trace ID, service, or operation.' : 'Send a real request through your project instrumentation to activate trace exploration.'}</p>{!q&&<Link to="/onboarding" className="mt-4 inline-flex text-sm font-medium text-[#16931F] hover:underline">Open setup flow</Link>}</div>:<div className="divide-y divide-[#DBE5D7]">{data.map(t=><Link key={t.traceId} to="/dashboard/trace/$traceId" params={{traceId:t.traceId}} className="flex items-center gap-4 p-4 hover:bg-muted focus-visible:bg-muted"><span className="grid h-8 w-8 place-items-center rounded-lg bg-secondary"><GitBranch className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{t.rootOperation}</p><p className="font-mono text-[11px] text-muted-foreground">{t.traceId} · {t.rootService}</p></div><div className="hidden items-center gap-2 sm:flex"><Clock3 className="h-3.5 w-3.5 text-muted-foreground"/><span className="font-mono text-xs">{t.durationMs}ms</span><Badge variant="outline">{t.spanCount} spans</Badge><Badge variant="outline">{t.status}</Badge></div><ChevronRight className="h-4 w-4 text-muted-foreground"/></Link>)}</div>}</CardContent></Card></div>}
function Empty(){return <Card><CardContent className="p-10 text-center"><p className="font-medium">Choose a project</p><p className="mt-1 text-sm text-muted-foreground">Select a project to inspect traces.</p></CardContent></Card>}
